import streamlit as st
import re
import unicodedata
from typing import Dict, List, Tuple, Optional
import pdfplumber
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from io import BytesIO
from dataclasses import dataclass, field
from datetime import datetime
import pandas as pd

# ============================================
# DATENMODELL
# ============================================

@dataclass
class VokabelEintrag:
    """Repräsentiert eine Hauptnummer mit mehreren Zeilen."""
    position: int
    griechisch: str
    stammzeilen: List[str] = field(default_factory=list)
    bedeutungen: List[str] = field(default_factory=list)
    gefunden: bool = False

# ============================================
# OMEGA-WORTSCHATZ – DER VOLLSTÄNDIGE WORTSCHATZ
# ============================================

class OmegaWortschatz:
    """Vollständige Implementierung des Omega-Wortschatzes."""
    
    def __init__(self):
        self.vocab_dict = {}
        self.synonyme = {}
        self._build_dictionary()
        self._build_synonyme()
    
    def _build_synonyme(self):
        self.synonyme = {
            "νόος": "νοῦς", "νόος": "νοῦς", "ἐσθίω": "ἔσθω",
            "Ζεύς": "Ζεύς", "ἐάω": "ἐάω", "θέλω": "ἐθέλω",
            "βιόω": "ζάω", "γῆ": "γαῖα", "θάλαττα": "θάλασσα",
            "πλείων": "πλέων", "σμικρός": "μικρός", "ξύν": "σύν",
            "τέσσαρες": "τέτταρες",
        }
    
    def _build_dictionary(self):
        # ============ ALPHA ============
        self.vocab_dict.update({
            "ἀγαθός": ("gut, anständig", "ἀγαθός, ή, όν", 
                      "3 Steigerungsreihen: 1) ἀμείνων/ἄμεινον, ἄριστος; 2) κρείττων/κρεῖττον, κράτιστος; 3) βελτίων/βέλτιον, βέλτιστος. τὸ ἀγαθόν - das Gute; τὰ ἀγαθά - die Güter"),
            "ἀγανακτέω": ("sich ärgern, unwillig sein", "ἀγανακτέω", ""),
            "ἀγγέλλω": ("melden, berichten", "ἀγγέλλω, ἀγγελῶ, ἤγγειλα, ἤγγελκα, ἤγγελμαι, ἤγγελθην", ""),
            "ἄγγελος": ("Bote", "ἄγγελος, ου, ὁ", ""),
            "ἀγνοέω": ("nicht wissen, nicht kennen", "ἀγνοέω", ""),
            "ἀγορά": ("Marktplatz, Versammlung", "ἀγορά, ᾶς, ἡ", ""),
            "ἀγρός": ("Acker, Feld", "ἀγρός, οῦ, ὁ", ""),
            "ἄγω": ("führen, treiben; ziehen, marschieren", "ἄγω, ἄξω, ἤγαγον, ἦχα, ἤγμαι, ἤχθην", ""),
            "ἀγών": ("Wettkampf, Kampf; Prozess", "ἀγών, ῶνος, ὁ", ""),
            "ἀδελφός": ("Bruder", "ἀδελφός, οῦ, ὁ", ""),
            "ἀδικέω": ("Unrecht tun", "ἀδικέω, ἀδικήσω, ἠδίκησα, ἠδίκηκα, ἠδίκημαι, ἠδικήθην", ""),
            "ἀδικία": ("Unrecht, Ungerechtigkeit", "ἀδικία, ας, ἡ", ""),
            "ἄδικος": ("ungerecht, unrecht", "ἄδικος, ον", ""),
            "ἀδύνατος": ("unfähig, machtlos; unmöglich", "ἀδύνατος, ον", ""),
            "ᾄδω": ("singen, besingen", "ᾄδω", ""),
            "ἀεί": ("immer; jeweils", "ἀεί", ""),
            "ἀθάνατος": ("unsterblich", "ἀθάνατος, ον", ""),
            "ἄθλιος": ("elend, unglücklich", "ἄθλιος, α, ον", ""),
            "ἄθλος": ("Wettkampf; Mühe", "ἄθλος, ου, ὁ", ""),
            "αἰδέομαι": ("scheuen, Ehrfurcht haben; respektieren", "αἰδέομαι, αἰδέσομαι, ἠδέσθην", ""),
            "αἰδώς": ("Scham; Ehrfurcht", "αἰδώς, όος, ἡ", ""),
            "αἱρέω": ("nehmen, ergreifen; zu Fall bringen; M. sich nehmen, wählen", "αἱρέω, αἱρήσω, εἷλον, ᾕρηκα, ᾕρημαι, ἡρέθην", ""),
            "αἴρω": ("hochheben, aufheben; absegeln, aufbrechen", "αἴρω, ἀρῶ, ἦρα, ἦρκα, ἦρμαι, ἦρθην", ""),
            "αἰσθάνομαι": ("wahrnehmen, merken", "αἰσθάνομαι, αἰσθήσομαι, ᾐσθόμην, ᾔσθημαι", ""),
            "αἰσχρός": ("hässlich; schändlich", "αἰσχρός, ά, όν", ""),
            "αἰσχύνομαι": ("sich schämen; respektieren", "αἰσχύνομαι, αἰσχυνοῦμαι, ᾐσχύνθην, ᾔσχυμμαι", ""),
            "αἰτέω": ("fordern, verlangen", "αἰτέω, αἰτήσω, ᾔτησα, ᾔτηκα, ᾔτημαι, ᾐτήθην", ""),
            "αἰτία": ("Grund, Ursache; Schuld", "αἰτία, ας, ἡ", ""),
            "αἴτιος": ("schuld, schuldig; Urheber", "αἴτιος, α, ον", ""),
            "ἀκοή": ("Gehör; Gerücht", "ἀκοή, ῆς, ἡ", ""),
            "ἀκολουθέω": ("folgen", "ἀκολουθέω", ""),
            "ἀκούω": ("hören", "ἀκούω, ἀκούσομαι, ἤκουσα, ἀκήκοα, ἠκούσθην", ""),
            "ἀκριβής": ("sorgfältig, genau", "ἀκριβής, ές", ""),
            "ἄκων": ("unfreiwillig, ungern", "ἄκων, ἄκουσα, ἄκον", ""),
            "ἀλήθεια": ("Wahrheit", "ἀλήθεια, ας, ἡ", ""),
            "ἀληθής": ("wahr, wahrhaftig", "ἀληθής, ές", ""),
            "ἀλίσκομαι": ("gefangen werden; überführt werden", "ἀλίσκομαι, ἁλώσομαι, ἑάλων, ἑάλωκα", ""),
            "ἀλλά": ("aber; sondern", "ἀλλά", ""),
            "ἀλλήλων": ("einander, gegenseitig", "ἀλλήλων, -οις/-αις, -ους/-ας/-α", ""),
            "ἄλλος": ("ein anderer", "ἄλλος, η, ο", ""),
            "ἅμα": ("zugleich; zusammen mit; während", "ἅμα", ""),
            "ἀμαθής": ("ungebildet, unwissend", "ἀμαθής, ές", ""),
            "ἁμαρτάνω": ("verfehlen, falsch machen; sündigen", "ἁμαρτάνω, ἁμαρτήσομαι, ἥμαρτον, ἡμάρτηκα, ἡμάρτημαι, ἡμαρτήθην", ""),
            "ἁμαρτία": ("Fehler, Verfehlung", "ἁμαρτία, ας, ἡ", ""),
            "ἀμελέω": ("sich nicht kümmern; vernachlässigen", "ἀμελέω", ""),
            "ἀμύνω": ("abwehren, fernhalten; helfen; M. sich verteidigen", "ἀμύνω, ἀμυνῶ, ἤμυνα", ""),
            "ἀμφί": ("um...herum", "ἀμφί", ""),
            "ἀμφισβητέω": ("bestreiten, sich streiten; behaupten", "ἀμφισβητέω", ""),
            "ἀμφότεροι": ("beide", "ἀμφότεροι, αι, α", ""),
            "ἄν": ("Modalpartikel", "ἄν", "Potentialis (Optativ), Irrealis (Ind. Impf./Aor.), Iterativ/Eventualis (Konjunktiv)"),
            "ἀνά": ("über...hin; hinauf; während", "ἀνά", ""),
            "ἀναγιγνώσκω": ("lesen, vorlesen", "ἀναγιγνώσκω", ""),
            "ἀναγκάζω": ("zwingen", "ἀναγκάζω", ""),
            "ἀναγκαῖος": ("notwendig", "ἀναγκαῖος, α, ον", ""),
            "ἀνάγκη": ("Notwendigkeit, Zwang", "ἀνάγκη, ης, ἡ", ""),
            "ἀναλαμβάνω": ("aufnehmen", "ἀναλαμβάνω", ""),
            "ἀναμιμνήσκω": ("erinnern; M. sich erinnern", "ἀναμιμνήσκω", ""),
            "ἀνδρεία": ("Tapferkeit", "ἀνδρεία, ας, ἡ", ""),
            "ἀνδρεῖος": ("tapfer", "ἀνδρεῖος, α, ον", ""),
            "ἄνευ": ("ohne", "ἄνευ", ""),
            "ἀνήρ": ("Mann", "ἀνήρ, ἀνδρός, ὁ", ""),
            "ἀνθρώπειος": ("menschlich", "ἀνθρώπειος, α, ον", ""),
            "ἄνθρωπος": ("Mensch", "ἄνθρωπος, ου, ὁ", ""),
            "ἀνίημι": ("loslassen; nachlassen", "ἀνίημι", ""),
            "ἀνίστημι": ("aufstellen; M. aufstehen, sich erheben", "ἀνίστημι", ""),
            "ἀνόητος": ("unvernünftig", "ἀνόητος, ον", ""),
            "ἀνόσιος": ("gottlos; unrecht", "ἀνόσιος, α, ον", ""),
            "ἀντί": ("anstelle von", "ἀντί", ""),
            "ἄξιος": ("würdig, wert; angemessen, richtig", "ἄξιος, ία, ιον", ""),
            "ἀξιόω": ("für würdig halten; fordern; glauben", "ἀξιόω, ἀξιώσω, ἠξίωσα, ἠξίωκα, ἠξίωμαι, ἠξιώθην", ""),
            "ἀπαλλάττω": ("entfernen; befreien", "ἀπαλλάττω, ἀπαλλάξω, ἀπήλλαξα, ἀπήλλαχα, ἀπήλλαγμαι, ἀπηλλάχθην", ""),
            "ἅπας": ("all, ganz, jeder", "ἅπας, ἅπασα, ἅπαν", ""),
            "ἄπειμι": ("weggehen", "ἄπειμι", ""),
            "ἀπιστέω": ("nicht glauben; misstrauen", "ἀπιστέω", ""),
            "ἀπό": ("von, seit", "ἀπό", ""),
            "ἀποδείκνυμι": ("zeigen, darlegen, beweisen", "ἀποδείκνυμι", ""),
            "ἀποδέχομαι": ("annehmen; aufnehmen", "ἀποδέχομαι", ""),
            "ἀποδιδράσκω": ("weglaufen, entlaufen", "ἀποδιδράσκω", ""),
            "ἀποθνῄσκω": ("sterben; tot sein", "ἀποθνῄσκω, ἀποθανοῦμαι, ἀπέθανον, τέθνηκα", ""),
            "ἀποκρίνομαι": ("antworten", "ἀποκρίνομαι, ἀποκρινοῦμαι, ἀπεκρινάμην, ἀπεκρίθην", ""),
            "ἀπόκρισις": ("Antwort", "ἀπόκρισις, εως, ἡ", ""),
            "ἀποκτείνω": ("töten", "ἀποκτείνω, ἀποκτενῶ, ἀπέκτεινα, ἀπέκτονα", ""),
            "ἀπόλλυμι": ("zugrunde richten; verlieren", "ἀπόλλυμι, ἀπολῶ, ἀπώλεσα", "Aor. M. ἀπωλόμην, Perf. ἀπολώλεκα/ἀπόλωλα"),
            "ἀπολογέομαι": ("sich verteidigen", "ἀπολογέομαι", ""),
            "ἀπορία": ("Ratlosigkeit; Mangel", "ἀπορία, ας, ἡ", ""),
            "ἀποφαίνω": ("zeigen, darlegen", "ἀποφαίνω", ""),
            "ἅπτομαι": ("berühren, anfassen; sich befassen mit", "ἅπτομαι, ἅψομαι, ἡψάμην, ἧμμαι, ἥφθην", ""),
            "ἄρα": ("also, folglich", "ἄρα", ""),
            "ἆρα": ("Fragepartikel", "ἆρα", ""),
            "ἀργύριον": ("Silber, Geld", "ἀργύριον, ου, τό", ""),
            "ἀρετή": ("Tüchtigkeit, Tugend; Tapferkeit; Leistung", "ἀρετή, ῆς, ἡ", ""),
            "ἀριθμός": ("Zahl", "ἀριθμός, οῦ, ὁ", ""),
            "ἄριστος": ("der beste, tüchtigste", "ἄριστος, η, ον", "Superlativ von ἀγαθός"),
            "ἀρκέω": ("stark genug sein, genügen", "ἀρκέω", ""),
            "ἀρχαῖος": ("alt, früher", "ἀρχαῖος, α, ον", ""),
            "ἀρχή": ("Anfang; Herrschaft, Reich; Amt", "ἀρχή, ῆς, ἡ", ""),
            "ἄρχομαι": ("anfangen", "ἄρχομαι, ἄρξομαι, ἠρξάμην", ""),
            "ἄρχω": ("herrschen; den Anfang machen", "ἄρχω, ἄρξω, ἦρξα, ἦργμαι, ἦρχθην", ""),
            "ἄρχων": ("Herrscher, Anführer; Archont", "ἄρχων, οντος, ὁ", ""),
            "ἀσθενής": ("schwach, kraftlos; krank", "ἀσθενής, ές", ""),
            "ἀσκέω": ("üben, ausüben", "ἀσκέω", ""),
            "ἄστρον": ("Stern", "ἄστρον, ου, τό", ""),
            "ἄτε": ("da, weil", "ἄτε", "objektiver Grund im Unterschied zu ὡς + Part."),
            "ἄτοπος": ("unpassend, seltsam", "ἄτοπος, ον", ""),
            "αὖ": ("wieder; wiederum", "αὖ, αὖθις", ""),
            "αὐτίκα": ("sofort", "αὐτίκα", ""),
            "αὐτός": ("selbst; derselbe", "αὐτός, ή, ό", "Personalpronomen der 3.Ps."),
            "αὐτοῦ": ("ebendort", "αὐτοῦ", ""),
            "ἀφαιρέω": ("wegnehmen", "ἀφαιρέω, ἀφαιρήσω, ἀφεῖλον, ἀφήρηκα, ἀφήρημαι, ἀφηρέθην", ""),
            "ἀφίημι": ("losschicken; freilassen", "ἀφίημι, ἀφήσω, ἀφῆκα, ἀφεῖκα, ἀφεῖμαι, ἀφείθην", ""),
            "ἀφικνέομαι": ("ankommen", "ἀφικνέομαι, ἀφίξομαι, ἀφικόμην, ἀφῖγμαι", ""),
            "ἄφρων": ("unvernünftig", "ἄφρων, ον", ""),
            "ἄχθομαι": ("unwillig sein, sich ärgern", "ἄχθομαι", ""),
        })
        
        # ============ BETA ============
        self.vocab_dict.update({
            "βαίνω": ("gehen", "βαίνω, βήσομαι, ἔβην, βέβηκα", ""),
            "βάλλω": ("werfen; treffen", "βάλλω, βαλῶ, ἔβαλον, βέβληκα, βέβλημαι, ἐβλήθην", ""),
            "βάρβαρος": ("nichtgriechisch", "βάρβαρος, ον", ""),
            "βασιλεύς": ("König", "βασιλεύς, έως, ὁ", ""),
            "βέβαιος": ("fest, beständig, zuverlässig", "βέβαιος, α, ον", ""),
            "βελτίων": ("besser", "βελτίων, βέλτιον", "Komp. zu ἀγαθός, Superl. βέλτιστος"),
            "βιάζομαι": ("zwingen, überwältigen", "βιάζομαι", ""),
            "βιβλίον": ("Buch", "βιβλίον, ου, τό", ""),
            "βίος": ("Leben; Lebensunterhalt", "βίος, ου, ὁ", ""),
            "βιόω": ("leben", "βιόω, βιώσομαι, ἐβίων, βεβίωκα", ""),
            "βλάπτω": ("schädigen, schaden", "βλάπτω, βλάψω, ἔβλαψα, βέβλαφα, βέβλαμμαι, ἐβλάβην", ""),
            "βλέπω": ("blicken, sehen", "βλέπω, βλέψομαι, ἔβλεψα", ""),
            "βοηθέω": ("helfen", "βοηθέω, βοηθήσω, ἐβοήθησα, βεβοήθηκα", ""),
            "βουλεύω": ("beraten, überlegen; beschließen", "βουλεύω, βουλεύσω, ἐβούλευσα, βεβούλευκα, βεβούλευμαι, ἐβουλεύθην", ""),
            "βουλή": ("Plan, Rat, Absicht; Ratsversammlung", "βουλή, ῆς, ἡ", ""),
            "βούλομαι": ("wollen", "βούλομαι, βουλήσομαι, βεβούλημαι, ἐβουλήθην", ""),
            "βοῦς": ("Rind, Kuh", "βοῦς, βοός, ὁ/ἡ", ""),
            "βροτός": ("sterblich", "βροτός, ή, όν", ""),
        })
        
        # ============ GAMMA ============
        self.vocab_dict.update({
            "γάμος": ("Hochzeit, Ehe", "γάμος, ου, ὁ", ""),
            "γάρ": ("denn, nämlich", "γάρ", ""),
            "γε": ("jedenfalls; wenigstens", "γε", "häufig unübersetzt"),
            "γελάω": ("lachen; auslachen", "γελάω, γελάσομαι, ἐγέλασα", ""),
            "γενναῖος": ("edel, adlig; tüchtig; echt", "γενναῖος, α, ον", ""),
            "γένος": ("Geschlecht, Gattung, Abstammung", "γένος, ους, τό", ""),
            "γέρων": ("alter Mann, Greis", "γέρων, οντος, ὁ", ""),
            "γεωργός": ("Bauer", "γεωργός, οῦ, ὁ", ""),
            "γῆ": ("Erde; Land", "γῆ, γῆς, ἡ", ""),
            "γίγνομαι": ("werden; entstehen; geschehen", "γίγνομαι, γενήσομαι, ἐγενόμην, γέγονα/γεγένημαι", ""),
            "γιγνώσκω": ("erkennen, kennen", "γιγνώσκω, γνώσομαι, ἔγνων, ἔγνωκα, ἔγνωσμαι, ἐγνώσθην", ""),
            "γλυκύς": ("süß, lieb", "γλυκύς, εῖα, ύ", ""),
            "γλῶττα": ("Zunge; Sprache", "γλῶττα, ης, ἡ", ""),
            "γνώμη": ("Verstand, Einsicht; Gesinnung, Meinung", "γνώμη, ης, ἡ", ""),
            "γοῦν": ("jedenfalls, wenigstens", "γοῦν", ""),
            "γράμμα": ("Buchstabe; Schrift; Wissenschaft", "γράμμα, ατος, τό", "τὰ γράμματα - Literatur, Wissenschaften"),
            "γράφω": ("schreiben", "γράφω, γράψω, ἔγραψα, γέγραφα, γέγραμμαι, ἐγράφην", "γραφὴν γράφομαι - anklagen"),
            "γυμνάζω": ("üben, trainieren", "γυμνάζω", ""),
            "γυμνός": ("nackt; unbewaffnet", "γυμνός, ή, όν", ""),
            "γυνή": ("Frau", "γυνή, γυναικός, ἡ", ""),
        })
        
        # ============ DELTA ============
        self.vocab_dict.update({
            "δαιμόνιον": ("göttliches Wesen, göttliche Stimme", "δαιμόνιον, ου, τό", ""),
            "δαίμων": ("Gottheit; Götterwille", "δαίμων, ονος, ὁ/ἡ", ""),
            "δέ": ("aber; und", "δέ", ""),
            "δέδοικα": ("fürchten", "δέδοικα/δέδια, δείσομαι, ἔδεισα", "Perfekt mit Präsensbedeutung"),
            "δεῖ": ("es ist nötig; man muss", "δεῖ, δεήσει, ἔδει", "verneint: man darf nicht"),
            "δείκνυμι": ("zeigen; nachweisen", "δείκνυμι, δείξω, ἔδειξα, δέδειχα, δέδειγμαι, ἐδείχθην", ""),
            "δειλός": ("furchtsam, feige; elend", "δειλός, ή, όν", ""),
            "δεινός": ("gewaltig; furchtbar; tüchtig", "δεινός, ή, όν", ""),
            "δεῖπνον": ("Mahlzeit, Abendessen", "δεῖπνον, ου, τό", ""),
            "δέκα": ("zehn", "δέκα", ""),
            "δένδρον": ("Baum", "δένδρον, ου, τό", ""),
            "δέομαι": ("bedürfen, nötig haben; bitten", "δέομαι, δεήσομαι, ἐδεήθην", "δέομαί τινος τί - jdn. um etw. bitten"),
            "δέον": ("da es nötig ist", "δέον", "τὸ δέον/τὰ δέοντα - das Nötige"),
            "δεσπότης": ("Herr, Herrscher", "δεσπότης, ου, ὁ", ""),
            "δεῦρο": ("hierher", "δεῦρο", ""),
            "δεύτερος": ("der zweite", "δεύτερος, α, ον", ""),
            "δέχομαι": ("annehmen, aufnehmen", "δέχομαι, δέξομαι, ἐδεξάμην, δέδεγμαι, ἐδέχθην", ""),
            "δέω": ("fesseln, binden", "δέω", ""),
            "δή": ("also, wirklich", "δή", "oft zur Verstärkung"),
            "δῆλος": ("offensichtlich, klar", "δῆλος, η, ον", ""),
            "δηλόω": ("klar machen, zeigen", "δηλόω, δηλώσω, ἐδήλωσα, δεδήλωκα, ἐδηλώθην", ""),
            "δημιουργός": ("Handwerker; Schöpfer", "δημιουργός, οῦ, ὁ", ""),
            "δῆμος": ("Gemeinde; Volk", "δῆμος, ου, ὁ", ""),
            "δημόσιος": ("staatlich, öffentlich", "δημόσιος, α, ον", "δημοσίᾳ - öffentlich, Ggs. ἰδίᾳ"),
            "δήπου": ("doch wohl, sicherlich", "δήπου", ""),
            "δῆτα": ("bestimmt, durchaus", "δῆτα", ""),
            "διά": ("durch (+Gen.); wegen (+Akk.)", "διά", "διὰ τί - weshalb; διὰ τοῦτο - deshalb"),
            "διαβάλλω": ("verleumden", "διαβάλλω", ""),
            "διαλέγομαι": ("sich unterhalten", "διαλέγομαι, διαλέξομαι, διελέχθην, διείλεγμαι", ""),
            "διανοέομαι": ("denken, beabsichtigen", "διανοέομαι", ""),
            "διαφέρω": ("sich unterscheiden", "διαφέρω, διοίσω, διήνεγκον, διενήνοχα, διενήνεγμαι", "διαφέρει - es macht einen Unterschied"),
            "διαφθείρω": ("verderben, vernichten", "διαφθείρω, διαφθερῶ, διέφθειρα, διέφθαρκα, διέφθαρμαι, διεφθάρην", ""),
            "διδάσκαλος": ("Lehrer", "διδάσκαλος, ου, ὁ", ""),
            "διδάσκω": ("lehren, unterrichten", "διδάσκω, διδάξω, ἐδίδαξα, δεδίδαχα, δεδίδαγμαι, ἐδιδάχθην", ""),
            "δίδωμι": ("geben", "δίδωμι, δώσω, ἔδωκα, δέδωκα, δέδομαι, ἐδόθην", "δίκην δίδωμι - bestraft werden"),
            "διέρχομαι": ("hindurchgehen; erörtern", "διέρχομαι", ""),
            "δικάζω": ("Recht sprechen, urteilen", "δικάζω", "δικάζομαι - prozessieren"),
            "δίκαιος": ("gerecht, richtig", "δίκαιος, ία, ιον", "δικαιός εἰμι + Inf. - berechtigt sein"),
            "δικαιοσύνη": ("Gerechtigkeit", "δικαιοσύνη, ης, ἡ", ""),
            "δικαιόω": ("für recht halten, fordern", "δικαιόω", ""),
            "δικαστήριον": ("Gericht", "δικαστήριον, ου, τό", ""),
            "δικαστής": ("Richter", "δικαστής, οῦ, ὁ", ""),
            "δίκη": ("Recht, Gerechtigkeit; Prozess, Strafe", "δίκη, ης, ἡ", "δίκην δίδωμι - bestraft werden"),
            "διό": ("deshalb", "διό", ""),
            "διώκω": ("verfolgen; anklagen", "διώκω, διώξομαι, ἐδίωξα, δεδίωχα, δεδίωγμαι, ἐδιώχθην", ""),
            "δοκέω": ("scheinen; meinen, glauben", "δοκέω, δόξω, ἔδοξα", "δοκεῖ μοι - ich beschließe"),
            "δόξα": ("Meinung; Schein; Ruf", "δόξα, ης, ἡ", ""),
            "δοξάζω": ("meinen", "δοξάζω", ""),
            "δοῦλος": ("Sklave, Knecht", "δοῦλος, ου, ὁ", ""),
            "δράω": ("tun, handeln", "δράω, δράσω, ἔδρασα, δέδρακα, δέδραμαι, ἐδράσθην", ""),
            "δύναμαι": ("können, vermögen; bedeuten", "δύναμαι, δυνήσομαι, ἐδυνήθην, δεδύνημαι", ""),
            "δύναμις": ("Kraft, Macht, Fähigkeit", "δύναμις, εως, ἡ", ""),
            "δυνατός": ("fähig; mächtig; möglich", "δυνατός, ή, όν", ""),
            "δύο": ("zwei", "δύο", ""),
            "δῶρον": ("Geschenk, Gabe", "δῶρον, ου, τό", ""),
        })
        
        # ============ EPSILON ============
        self.vocab_dict.update({
            "ἐάν": ("wenn; immer wenn", "ἐάν", ""),
            "ἑαυτοῦ": ("seiner/ihrer selbst, sich", "ἑαυτοῦ, ἑαυτῆς, ἑαυτοῦ", "Reflexivpronomen der 3.Ps."),
            "ἐάω": ("lassen, zulassen", "ἐάω, ἐάσω, εἴασα", ""),
            "ἐγώ": ("ich", "ἐγώ, ἐμοῦ", ""),
            "ἐθέλω": ("wollen; bereit sein", "ἐθέλω, ἐθελήσω, ἠθέλησα, ἠθέληκα", ""),
            "ἔθνος": ("Volk, Volksstamm", "ἔθνος, ους, τό", ""),
            "ἔθος": ("Sitte; Gewohnheit", "ἔθος, ους, τό", ""),
            "εἰ": ("wenn, falls; ob", "εἰ", ""),
            "εἰ γάρ": ("wenn doch, hoffentlich", "εἰ γάρ", ""),
            "εἶδος": ("Gestalt, Aussehen; Idee", "εἶδος, ους, τό", ""),
            "εἴδωλον": ("Bild, Götterbild", "εἴδωλον, ου, τό", ""),
            "εἶεν": ("nun gut", "εἶεν", ""),
            "εἶθε": ("wenn doch, hoffentlich", "εἶθε", ""),
            "εἰκός": ("Wahrscheinlichkeit; Angemessenheit", "εἰκός, ότος, τό", "εἰκός ἐστι - es ist wahrscheinlich/angemessen"),
            "εἰκών": ("Bild; Statue", "εἰκών, όνος, ἡ", ""),
            "εἰμί": ("sein", "εἰμί, ἔσομαι, ἦν", "ἔστιν - es gibt, es ist möglich"),
            "εἶμι": ("gehen", "εἶμι", "Futur zu ἔρχομαι"),
            "εἶπερ": ("wenn wirklich", "εἶπερ", ""),
            "εἰρήνη": ("Friede", "εἰρήνη, ης, ἡ", ""),
            "εἷς": ("einer", "εἷς, μία, ἕν", ""),
            "εἰς": ("in...hinein; zu...hin", "εἰς", ""),
            "εἶτα": ("da, dann; ferner", "εἶτα", ""),
            "εἴτε...εἴτε": ("sei es... sei es", "εἴτε...εἴτε", ""),
            "εἴωθα": ("gewohnt sein", "εἴωθα", "Perfekt mit Präsensbedeutung"),
            "ἐκ": ("aus; seit; infolge von", "ἐκ, ἐξ", ""),
            "ἕκαστος": ("jeder", "ἕκαστος, ἑκάστη, ἕκαστον", ""),
            "ἑκάστοτε": ("jedesmal", "ἑκάστοτε", ""),
            "ἑκάτερος": ("jeder von beiden", "ἑκάτερος, ἑκατέρα, ἑκάτερον", ""),
            "ἑκατόν": ("hundert", "ἑκατόν", ""),
            "ἐκβάλλω": ("hinauswerfen, vertreiben", "ἐκβάλλω, ἐκβαλῶ, ἐξέβαλον, ἐκβέβληκα, ἐκβέβλημαι, ἐξεβλήθην", ""),
            "ἐκεῖ": ("dort", "ἐκεῖ", ""),
            "ἐκεῖνος": ("jener", "ἐκεῖνος, η, ο", ""),
            "ἐκκλησία": ("Volksversammlung; Kirche", "ἐκκλησία, ας, ἡ", ""),
            "ἐκπλήττω": ("erschrecken", "ἐκπλήττω", ""),
            "ἑκών": ("freiwillig, willentlich", "ἑκών, ἑκοῦσα, ἑκόν", ""),
            "ἐλάττων": ("kleiner, geringer", "ἐλάττων, ον", "Komp. zu μικρός/ὀλίγος"),
            "ἐλαύνω": ("treiben, marschieren", "ἐλαύνω, ἐλῶ, ἤλασα, ἐλήλακα, ἐλήλαμαι, ἠλάθην", ""),
            "ἐλέγχω": ("prüfen; widerlegen", "ἐλέγχω", ""),
            "ἐλευθερία": ("Freiheit", "ἐλευθερία, ας, ἡ", ""),
            "ἐλεύθερος": ("frei", "ἐλεύθερος, α, ον", ""),
            "ἐλπίζω": ("hoffen, erwarten", "ἐλπίζω", ""),
            "ἐλπίς": ("Hoffnung, Erwartung", "ἐλπίς, ίδος, ἡ", ""),
            "ἐμαυτοῦ": ("meiner selbst", "ἐμαυτοῦ, ῆς, οῦ", "Reflexivpronomen 1.Ps."),
            "ἐμός": ("mein", "ἐμός, ή, όν", ""),
            "ἔμπειρος": ("erfahren, kundig", "ἔμπειρος, ον", ""),
            "ἐμπίπτω": ("hineinfallen, geraten in", "ἐμπίπτω", ""),
            "ἔμπροσθεν": ("vorne; früher", "ἔμπροσθεν", ""),
            "ἐν": ("in, an, auf, bei; während", "ἐν", ""),
            "ἐν ᾧ": ("während", "ἐν ᾧ", ""),
            "ἐναντίος": ("gegenüber; entgegengesetzt", "ἐναντίος, α, ον", "ὁ ἐναντίος - Gegner"),
            "ἔνεκα": ("wegen; um...willen", "ἔνεκα", ""),
            "ἔνθα": ("da, dort", "ἔνθα", ""),
            "ἐνθάδε": ("hier", "ἐνθάδε", ""),
            "ἐνθυμέομαι": ("bedenken, überlegen", "ἐνθυμέομαι", ""),
            "ἔνιοι": ("einige", "ἔνιοι, αι, α", ""),
            "ἐνίοτε": ("manchmal", "ἐνίοτε", ""),
            "ἐννοέω": ("bedenken; begreifen", "ἐννοέω", ""),
            "ἐνταῦθα": ("hier; dort", "ἐνταῦθα", ""),
            "ἐντυγχάνω": ("treffen auf, geraten in", "ἐντυγχάνω, ἐντεύξομαι, ἐνέτυχον, ἐντετύχηκα", ""),
            "ἕξ": ("sechs", "ἕξ", ""),
            "ἐξ οὗ": ("seitdem", "ἐξ οὗ", ""),
            "ἔξεστι": ("es ist möglich; es ist erlaubt", "ἔξεστι", ""),
            "ἐξετάζω": ("untersuchen, prüfen", "ἐξετάζω", ""),
            "ἔοικα": ("scheinen; gleichen", "ἔοικα", "Perfekt mit Präsensbedeutung"),
            "ἐπαγγέλλομαι": ("ankündigen; angeben", "ἐπαγγέλλομαι", ""),
            "ἐπαινέω": ("loben", "ἐπαινέω", ""),
            "ἔπαινος": ("Lob", "ἔπαινος, ου, ὁ", ""),
            "ἐπεί": ("als, nachdem; da, weil", "ἐπεί", ""),
            "ἐπειδή": ("als, nachdem; da, weil", "ἐπειδή", ""),
            "ἔπειμι": ("hingehen; angreifen", "ἔπειμι", ""),
            "ἔπειτα": ("dann, darauf", "ἔπειτα", ""),
            "ἐπί": ("auf (+Gen.); bei (+Dat.); zu (+Akk.)", "ἐπί", ""),
            "ἐπιβουλεύω": ("einen Anschlag planen", "ἐπιβουλεύω", ""),
            "ἐπιδείκνυμι": ("vorzeigen, zur Schau stellen", "ἐπιδείκνυμι", ""),
            "ἐπιθυμέω": ("begehren, wollen", "ἐπιθυμέω", ""),
            "ἐπιθυμία": ("Begierde, Verlangen", "ἐπιθυμία, ας, ἡ", ""),
            "ἐπιλανθάνομαι": ("vergessen", "ἐπιλανθάνομαι, ἐπιλήσομαι, ἐπελαθόμην, ἐπιλέλησμαι", ""),
            "ἐπιμέλεια": ("Sorge, Fürsorge", "ἐπιμέλεια, ας, ἡ", ""),
            "ἐπιμελέομαι": ("sich kümmern", "ἐπιμελέομαι", ""),
            "ἐπίσταμαι": ("verstehen; wissen; können", "ἐπίσταμαι", ""),
            "ἐπιστήμη": ("Wissen, Wissenschaft", "ἐπιστήμη, ης, ἡ", ""),
            "ἐπιστολή": ("Brief", "ἐπιστολή, ῆς, ἡ", ""),
            "ἐπιτήδειος": ("geeignet, passend", "ἐπιτήδειος, ον", "τὰ ἐπιτήδεια - Lebensmittel"),
            "ἐπιτίθημι": ("darauflegen; zufügen", "ἐπιτίθημι", ""),
            "ἐπιτρέπω": ("überlassen; gestatten", "ἐπιτρέπω", ""),
            "ἐπιχειρέω": ("versuchen; angreifen", "ἐπιχειρέω", ""),
            "ἕπομαι": ("folgen", "ἕπομαι, ἕψομαι, ἑσπόμην", ""),
            "ἔπος": ("Wort", "ἔπος, ους, τό", ""),
            "ἐράω": ("lieben, begehren", "ἐράω", ""),
            "ἐργάζομαι": ("arbeiten, tun", "ἐργάζομαι, ἐργάσομαι, εἰργασάμην, εἴργασμαι", ""),
            "ἔργον": ("Werk, Arbeit; Tat", "ἔργον, ου, τό", ""),
            "ἔρημος": ("einsam, verlassen", "ἔρημος, η, ον", ""),
            "ἔρις": ("Streit, Zank", "ἔρις, ιδος, ἡ", ""),
            "ἔρχομαι": ("gehen, kommen", "ἔρχομαι, εἶμι, ἦλθον, ἐλήλυθα", ""),
            "ἔρως": ("Liebe, Verlangen", "ἔρως, ωτος, ὁ", ""),
            "ἐρωτάω": ("fragen", "ἐρωτάω, ἐρήσομαι, ἠρόμην", ""),
            "ἐσθίω": ("essen", "ἐσθίω", ""),
            "ἑσπέρα": ("Abend", "ἑσπέρα, ας, ἡ", ""),
            "ἔσχατος": ("letzter, äußerster", "ἔσχατος, η, ον", ""),
            "ἑταῖρος": ("Freund, Gefährte", "ἑταῖρος, ου, ὁ", ""),
            "ἕτερος": ("der andere", "ἕτερος, α, ον", ""),
            "ἔτι": ("noch", "ἔτι", ""),
            "ἕτοιμος": ("bereit", "ἕτοιμος, η, ον", ""),
            "ἔτος": ("Jahr", "ἔτος, ους, τό", ""),
            "εὖ": ("gut", "εὖ", ""),
            "εὐδαιμονία": ("Glück, Glückseligkeit", "εὐδαιμονία, ας, ἡ", ""),
            "εὐδαίμων": ("glücklich, selig", "εὐδαίμων, ον", ""),
            "εὐθύς": ("sofort", "εὐθύς", ""),
            "εὑρίσκω": ("finden, erfinden", "εὑρίσκω, εὑρήσω, ηὗρον/εὗρον, ηὕρηκα/εὕρηκα", ""),
            "εὐχή": ("Gebet, Bitte", "εὐχή, ῆς, ἡ", ""),
            "εὔχομαι": ("beten; erflehen", "εὔχομαι", ""),
            "ἐφίστημι": ("voranstellen", "ἐφίστημι", ""),
            "ἐχθρός": ("feindlich, verhasst", "ἐχθρός, ά, όν", "ὁ ἐχθρός - der Feind"),
            "ἔχω": ("haben, halten; können", "ἔχω, ἕξω/σχήσω, ἔσχον, ἔσχηκα", "εὖ ἔχω - es geht mir gut"),
        })
        
        # ============ ZETA ============
        self.vocab_dict.update({
            "Ζεύς": ("Zeus", "Ζεύς, Διός, ὁ", "νὴ Δία/μὰ Δία - bei Zeus!"),
            "ζηλόω": ("nacheifern, bewundern", "ζηλόω", ""),
            "ζημία": ("Strafe", "ζημία, ας, ἡ", ""),
            "ζητέω": ("suchen; untersuchen; streben", "ζητέω, ζητήσω, ἐζήτησα, ἐζήτηκα", ""),
            "ζήτησις": ("Untersuchung", "ζήτησις, εως, ἡ", ""),
            "ζάω": ("leben", "ζάω, ζήσω, ἔζησα, ἔζηκα", ""),
            "ζωή": ("Leben", "ζωή, ῆς, ἡ", ""),
            "ζῷον": ("Lebewesen; Tier", "ζῷον, ου, τό", ""),
        })
        
        # ============ ETA ============
        self.vocab_dict.update({
            "ἤ": ("oder; als", "ἤ", ""),
            "ἡγεμών": ("Führer, Anführer", "ἡγεμών, όνος, ὁ", ""),
            "ἡγέομαι": ("führen; glauben, meinen", "ἡγέομαι, ἡγήσομαι, ἡγησάμην", ""),
            "ἤδη": ("schon", "ἤδη", ""),
            "ἥδομαι": ("sich freuen", "ἥδομαι", ""),
            "ἡδονή": ("Vergnügen, Lust", "ἡδονή, ῆς, ἡ", ""),
            "ἡδύς": ("süß, angenehm", "ἡδύς, εῖα, ύ", ""),
            "ἦθος": ("Charakter, Wesensart", "ἦθος, ους, τό", ""),
            "ἥκω": ("kommen, da sein", "ἥκω, ἥξω", ""),
            "ἡλικία": ("Lebensalter", "ἡλικία, ας, ἡ", ""),
            "ἥλιος": ("Sonne", "ἥλιος, ου, ὁ", ""),
            "ἡμεῖς": ("wir", "ἡμεῖς, ἡμῶν, ἡμῖν, ἡμᾶς", ""),
            "ἡμέρα": ("Tag", "ἡμέρα, ας, ἡ", ""),
            "ἡμέτερος": ("unser", "ἡμέτερος, α, ον", ""),
            "ἥρως": ("Held, Halbgott", "ἥρως, ωος, ὁ", ""),
            "ἡσυχία": ("Ruhe", "ἡσυχία, ας, ἡ", "ἡσυχίαν ἄγω - Ruhe bewahren"),
            "ἥττων": ("geringer, schwächer", "ἥττων, ἧττον", "οὐδὲν ἧττον - trotzdem"),
        })
        
        # ============ THETA ============
        self.vocab_dict.update({
            "θάλαττα": ("Meer", "θάλαττα, ης, ἡ", ""),
            "θάνατος": ("Tod", "θάνατος, ου, ὁ", ""),
            "θάπτω": ("bestatten, begraben", "θάπτω", ""),
            "θαρρέω": ("kühn sein, mutig sein", "θαρρέω", ""),
            "θαυμάζω": ("staunen, bewundern", "θαυμάζω, θαυμάσομαι, ἐθαύμασα, τεθαύμακα", ""),
            "θαυμάσιος": ("erstaunlich, wunderbar", "θαυμάσιος, α, ον", ""),
            "θεάομαι": ("betrachten, anschauen", "θεάομαι, θεάσομαι, ἐθεασάμην, τεθέαμαι", ""),
            "θέατρον": ("Theater", "θέατρον, ου, τό", ""),
            "θεῖος": ("göttlich", "θεῖος, θεία, θεῖον", ""),
            "θεός": ("Gott, Göttin", "θεός, οῦ, ὁ/ἡ", ""),
            "θεραπεύω": ("verehren; pflegen", "θεραπεύω", ""),
            "θερμός": ("warm", "θερμός, ή, όν", ""),
            "θεωρέω": ("betrachten, zuschauen", "θεωρέω", ""),
            "θηράω": ("jagen, erjagen", "θηράω", ""),
            "θησαυρός": ("Schatzkammer, Schatz", "θησαυρός, οῦ, ὁ", ""),
            "θνητός": ("sterblich", "θνητός, ή, όν", ""),
            "θρόνος": ("Sessel, Thron", "θρόνος, ου, ὁ", ""),
            "θυγάτηρ": ("Tochter", "θυγάτηρ, τρός, ἡ", ""),
            "θυμός": ("Mut, Zorn; Herz, Gemüt", "θυμός, οῦ, ὁ", ""),
            "θύρα": ("Tür, Tor", "θύρα, ας, ἡ", ""),
            "θύω": ("opfern", "θύω, θύσω, ἔθυσα, τέθυκα", ""),
        })
        
        # ============ IOTA ============
        self.vocab_dict.update({
            "ἰατρική": ("Heilkunst", "ἰατρική, ῆς, ἡ", ""),
            "ἰατρός": ("Arzt", "ἰατρός, οῦ, ὁ", ""),
            "ἴδιος": ("eigen; privat", "ἴδιος, ία, ιον", "ἰδίᾳ - privat"),
            "ἰδιώτης": ("Privatmann, Laie", "ἰδιώτης, ου, ὁ", ""),
            "ἱερός": ("heilig, geweiht", "ἱερός, ά, όν", ""),
            "ἵημι": ("in Bewegung setzen", "ἵημι, ἥσω, ἧκα, εἷκα, εἷμαι, εἵθην", ""),
            "ἱκανός": ("ausreichend; geeignet", "ἱκανός, ή, όν", ""),
            "ἱκετεύω": ("anflehen", "ἱκετεύω", ""),
            "ἵνα": ("damit, um zu; wo", "ἵνα", ""),
            "ἵππος": ("Pferd", "ἵππος, ου, ὁ", ""),
            "ἴσος": ("gleich; gerecht", "ἴσος, η, ον", ""),
            "ἵστημι": ("stellen, hinstellen", "ἵστημι, στήσω, ἔστησα/ἔστην, ἔστηκα", ""),
            "ἰστορία": ("Forschung, Geschichte", "ἰστορία, ας, ἡ", ""),
            "ἰσχυρός": ("stark, kraftvoll", "ἰσχυρός, ά, όν", ""),
            "ἴσως": ("vielleicht", "ἴσως", ""),
        })
        
        # ============ KAPPA ============
        self.vocab_dict.update({
            "καθεύδω": ("schlafen", "καθεύδω", ""),
            "κάθημαι": ("sitzen", "κάθημαι", ""),
            "καί": ("und; auch, sogar", "καί", "καί...καί - sowohl...als auch, καὶ δὴ καί - und ganz besonders"),
            "καίπερ": ("obwohl", "καίπερ", ""),
            "καιρός": ("rechte Zeit, Gelegenheit", "καιρός, οῦ, ὁ", "κατὰ καιρόν - zur rechten Zeit"),
            "καίτοι": ("und doch", "καίτοι", ""),
            "καίω": ("anzünden, verbrennen", "καίω", ""),
            "κακός": ("schlecht, böse", "κακός, ή, όν", "κακῶς λέγω - schlecht reden"),
            "καλέω": ("rufen; nennen", "καλέω, καλῶ, ἐκάλεσα, κέκληκα, κέκλημαι, ἐκλήθην", "ὁ καλούμενος - der sogenannte"),
            "καλός": ("schön, gut", "καλός, ή, όν", ""),
            "καρδία": ("Herz", "καρδία, ας, ἡ", ""),
            "κατά": ("von...herab (+Gen.); gemäß (+Akk.)", "κατά", "κατὰ φύσιν - gemäß der Natur"),
            "κατανοέω": ("wahrnehmen, verstehen", "κατανοέω", ""),
            "κατασκευάζω": ("einrichten", "κατασκευάζω", ""),
            "καταφρονέω": ("verachten", "καταφρονέω", ""),
            "κατέχω": ("niederhalten, festhalten", "κατέχω", ""),
            "κατηγορέω": ("anklagen", "κατηγορέω", ""),
            "κεῖμαι": ("liegen", "κεῖμαι, κείσομαι", ""),
            "κελεύω": ("befehlen, auffordern", "κελεύω, κελεύσω, ἐκέλευσα", ""),
            "κερδαίνω": ("gewinnen", "κερδαίνω", ""),
            "κέρδος": ("Gewinn, Vorteil", "κέρδος, ους, τό", ""),
            "κεφαλή": ("Kopf", "κεφαλή, ῆς, ἡ", ""),
            "κινδυνεύω": ("in Gefahr sein; scheinen", "κινδυνεύω", ""),
            "κίνδυνος": ("Gefahr", "κίνδυνος, ου, ὁ", ""),
            "κινέω": ("bewegen", "κινέω", ""),
            "κλέπτω": ("stehlen", "κλέπτω", ""),
            "κοινός": ("gemeinsam", "κοινός, ή, όν", "κοινῇ - gemeinsam"),
            "κολάζω": ("bestrafen", "κολάζω", ""),
            "κομίζω": ("bringen, transportieren", "κομίζω", ""),
            "κόρη": ("Mädchen, Tochter", "κόρη, ης, ἡ", ""),
            "κοσμέω": ("ordnen, schmücken", "κοσμέω", ""),
            "κόσμος": ("Ordnung; Schmuck; Welt", "κόσμος, ου, ὁ", ""),
            "κρατέω": ("stärker sein; besiegen", "κρατέω, κρατήσω, ἐκράτησα", ""),
            "κράτος": ("Stärke, Macht", "κράτος, ους, τό", ""),
            "κρείττων": ("stärker, besser", "κρείττων, κρεῖττον", "Komp. zu ἀγαθός"),
            "κρίνω": ("unterscheiden; urteilen", "κρίνω, κρινῶ, ἔκρινα, κέκρικα", ""),
            "κρίσις": ("Entscheidung, Urteil", "κρίσις, εως, ἡ", ""),
            "κρύπτω": ("verbergen", "κρύπτω", ""),
            "κτάομαι": ("erwerben", "κτάομαι, κτήσομαι, ἐκτησάμην, κέκτημαι", "κέκτημαι - besitzen"),
            "κτῆμα": ("Besitz", "κτῆμα, ατος, τό", ""),
            "κύκλος": ("Kreis", "κύκλος, ου, ὁ", ""),
            "κύριος": ("Herr", "κύριος, ου, ὁ", ""),
            "κωλύω": ("hindern, abhalten", "κωλύω, κωλύσω, ἐκώλυσα", ""),
        })
        
        # ============ LAMDA ============
        self.vocab_dict.update({
            "λαμβάνω": ("nehmen, ergreifen; erhalten", "λαμβάνω, λήψομαι, ἔλαβον, εἴληφα, εἴλημμαι, ἐλήφθην", ""),
            "λανθάνω": ("verborgen sein", "λανθάνω, λήσω, ἔλαθον, λέληθα", "λανθάνω ποιῶν τι - etw. unbemerkt tun"),
            "λέγω": ("sagen, sprechen; nennen", "λέγω, ἐρῶ, εἶπον, εἴρηκα, εἴρημαι, ἐλέχθην/ἐρρήθην", "ὡς ἔπος εἰπεῖν - sozusagen"),
            "λείπω": ("lassen; verlassen", "λείπω, λείψω, ἔλιπον, λέλοιπα, λέλειμμαι, ἐλείφθην", ""),
            "λίθος": ("Stein", "λίθος, ου, ὁ", ""),
            "λογίζομαι": ("rechnen, überlegen", "λογίζομαι, λογιοῦμαι, ἐλογισάμην, λελόγισμαι", ""),
            "λόγος": ("Wort, Rede; Gedanke; Erzählung", "λόγος, ου, ὁ", "λόγον δίδωμι - Rechenschaft ablegen"),
            "λοιπός": ("übrig", "λοιπός, ή, όν", "τὸ λοιπόν - künftig"),
            "λυπέω": ("betrüben", "λυπέω", ""),
            "λύπη": ("Schmerz, Leid", "λύπη, ης, ἡ", ""),
            "λύω": ("lösen, auflösen", "λύω, λύσω, ἔλυσα, λέλυκα, λέλυμαι, ἐλύθην", ""),
        })
        
        # ============ MY ============
        self.vocab_dict.update({
            "μάθημα": ("Lerngegenstand, Kenntnis", "μάθημα, ατος, τό", ""),
            "μαθητής": ("Schüler", "μαθητής, οῦ, ὁ", ""),
            "μαίνομαι": ("rasen, wüten", "μαίνομαι", ""),
            "μακάριος": ("glückselig, selig", "μακάριος, α, ον", ""),
            "μακρός": ("lang, groß", "μακρός, ά, όν", ""),
            "μάλα": ("sehr", "μάλα, μᾶλλον, μάλιστα", ""),
            "μάλιστα": ("am meisten, besonders", "μάλιστα", ""),
            "μᾶλλον": ("mehr, lieber", "μᾶλλον", "μᾶλλον δέ - vielmehr"),
            "μανθάνω": ("lernen; verstehen", "μανθάνω, μαθήσομαι, ἔμαθον, μεμάθηκα", ""),
            "μάντις": ("Seher, Wahrsager", "μάντις, εως, ὁ", ""),
            "μαρτυρέω": ("bezeugen", "μαρτυρέω", ""),
            "μάρτυς": ("Zeuge", "μάρτυς, υρος, ὁ/ἡ", ""),
            "μάχη": ("Kampf", "μάχη, ης, ἡ", ""),
            "μάχομαι": ("kämpfen", "μάχομαι, μαχοῦμαι, ἐμαχεσάμην, μεμάχημαι", ""),
            "μέγας": ("groß, bedeutend", "μέγας, μεγάλη, μέγα", ""),
            "μέγεθος": ("Größe", "μέγεθος, ους, τό", ""),
            "μείς": ("Monat", "μείς, μηνός, ὁ", ""),
            "μέλει": ("es liegt am Herzen", "μέλει", "μέλει μοί τινος - ich kümmere mich um etw."),
            "μέλλω": ("im Begriff sein; sollen; zögern", "μέλλω, μελλήσω, ἐμέλλησα", "τὰ μέλλοντα - die Zukunft"),
            "μέλος": ("Glied; Lied", "μέλος, ους, τό", ""),
            "μέν": ("zwar", "μέν", "μέν...δέ - zwar...aber"),
            "μέντοι": ("freilich, allerdings", "μέντοι", ""),
            "μένω": ("bleiben, warten", "μένω, μενῶ, ἔμεινα, μεμένηκα", ""),
            "μέρος": ("Teil", "μέρος, ους, τό", "τὸ ἐμὸν μέρος - was mich betrifft"),
            "μέσος": ("mittlerer, mitten", "μέσος, η, ον", ""),
            "μετά": ("mit (+Gen.); nach (+Akk.)", "μετά", ""),
            "μετέχω": ("Anteil haben", "μετέχω", ""),
            "μέτρον": ("Maß", "μέτρον, ου, τό", ""),
            "μή": ("nicht", "μή", ""),
            "μηδέ": ("und nicht, auch nicht", "μηδέ", ""),
            "μηδείς": ("niemand, nichts", "μηδείς, μηδεμία, μηδέν", ""),
            "μήν": ("wahrlich", "μήν", ""),
            "μήτηρ": ("Mutter", "μήτηρ, τρός, ἡ", ""),
            "μηχανή": ("Kunstgriff, Mittel, Maschine", "μηχανή, ῆς, ἡ", ""),
            "μικρός": ("klein", "μικρός, ά, όν", "μικροῦ δεῖν - beinahe"),
            "μιμέομαι": ("nachahmen", "μιμέομαι", ""),
            "μιμνήσκω": ("erinnern", "μιμνήσκω", ""),
            "μισέω": ("hassen", "μισέω", ""),
            "μνήμη": ("Gedächtnis, Andenken", "μνήμη, ης, ἡ", ""),
            "μοῖρα": ("Anteil; Schicksal", "μοῖρα, ας, ἡ", ""),
            "μόνος": ("allein, einzig", "μόνος, η, ον", "μόνον - nur"),
            "μῦθος": ("Wort; Erzählung", "μῦθος, ου, ὁ", ""),
            "μύριοι": ("zehntausend", "μύριοι, αι, α", ""),
        })
        
        # ============ NY ============
        self.vocab_dict.update({
            "ναί": ("ja", "ναί", ""),
            "ναός": ("Tempel", "ναός, οῦ, ὁ", ""),
            "ναῦς": ("Schiff", "ναῦς, νεώς, ἡ", ""),
            "νεκρός": ("tot; Leichnam", "νεκρός, ά, όν", ""),
            "νέμω": ("zuteilen; weiden", "νέμω", ""),
            "νέος": ("neu, jung", "νέος, α, ον", "οἱ νέοι - die jungen Männer"),
            "νῆσος": ("Insel", "νῆσος, ου, ἡ", ""),
            "νικάω": ("siegen, besiegen", "νικάω, νικήσω, ἐνίκησα, νενίκηκα", ""),
            "νίκη": ("Sieg", "νίκη, ης, ἡ", ""),
            "νοέω": ("denken; erkennen", "νοέω", ""),
            "νομίζω": ("glauben, meinen; anerkennen", "νομίζω, νομιῶ, ἐνόμισα, νενόμικα", ""),
            "νόμιμος": ("gesetzlich", "νόμιμος, η, ον", ""),
            "νόμος": ("Gesetz; Sitte", "νόμος, ου, ὁ", ""),
            "νόσος": ("Krankheit", "νόσος, ου, ἡ", ""),
            "νοῦς": ("Verstand, Geist", "νοῦς, νοῦ, ὁ", "τὸν νοῦν προσέχειν - achten auf"),
            "νῦν": ("nun", "νῦν", ""),
            "νύξ": ("Nacht", "νύξ, νυκτός, ἡ", "νυκτός - nachts"),
        })
        
        #
